const mongoose = require('mongoose');

const newsPostSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Please add a title'],
      trim: true,
      maxlength: 150
    },
    category: {
      // 'match-report' is auto-generated (see services/matchArticleGenerator.js);
      // 'international' is a placeholder for a future curated/external global-news
      // feed - not populated by anything yet, added now so that later addition
      // doesn't need another schema migration.
      type: String,
      enum: ['general', 'tournament-update', 'match-report', 'club-news', 'tips', 'international'],
      default: 'general'
    },
    body: {
      type: String,
      required: [true, 'Please add content'],
      maxlength: 10000
    },
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    // The tournament this article is about, if any - drives the personalized
    // "your tournaments" news feed (see newsController.getMyFeed). Null for
    // general/global news.
    tournament: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Tournament',
      default: null
    },
    match: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Match',
      default: null
    },
    // The standout player this article is about (century-maker, five-wicket
    // hero, etc.) - null for general recaps with no single standout performance.
    heroPlayer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Player',
      default: null
    },
    isAutoGenerated: {
      type: Boolean,
      default: false
    }
  },
  {
    timestamps: true
  }
);

newsPostSchema.index({ createdAt: -1 });
newsPostSchema.index({ tournament: 1, createdAt: -1 });

module.exports = mongoose.model('NewsPost', newsPostSchema);
