"""Out-of-sample evaluation of the win-probability model. Run by CI; results committed.

WHAT THIS EVALUATES, PRECISELY. It fits a fresh model on the training split and scores it on a
held-out set of MATCHES. The deployed artifact is refit on 100% of the data (standard practice),
so these numbers estimate the generalisation of the PROCEDURE, not of that exact pickle. That
distinction was previously neither made nor disclosed; it is stated here and in the emitted
metrics.json so nobody has to re-derive it.

PROVENANCE, WHICH BOUNDS EVERY NUMBER BELOW. data/real_matches.csv is extracted from this app's own
completed matches, but those matches were generated by backend/src/scripts/matchSimulator.js, which
draws every ball from fixed distributions independent of batter, bowler, team and match state. The
LABELS are genuine outcomes of played-out innings; the CRICKET is a simulator. Nothing here is
evidence about real cricket. See documentation/ai-engine-audit.md §2.
"""

import json
import os
import subprocess
from datetime import datetime, timezone

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import brier_score_loss, log_loss

FEATURES = ['overs_remaining', 'wickets_down', 'current_run_rate', 'target_score']
RANDOM_STATE = 42
HERE = os.path.dirname(os.path.abspath(__file__))

# CI gate. Set from the pre-remediation measurement (0.1563) with headroom for the sampling noise
# of a 115-match holdout. This is a REGRESSION gate - it catches the model getting worse - not a
# claim that 0.18 is good.
BRIER_CEILING = 0.18


def match_level_split(df, holdout_frac=0.2, seed=RANDOM_STATE):
    """Split by match_id, never by row.

    Rows from the same match share one outcome label and a smooth feature trajectory, so a
    row-level split would put near-duplicate rows carrying the same label in both train and test.
    That is the standard way win-probability models report accuracy that is pure memorisation.

    TEMPORAL GUARD (E6/AT-E6.2). This split is random over match ids, which is sound only while
    all matches are contemporaneous. Every match in the current file was created inside a ~20
    second window, so there is no chronology to violate. The moment real pilot matches accumulate,
    a random split trains on later matches and tests on earlier ones. The assertion below fails
    loudly at that point rather than silently leaking.
    """
    if 'match_date' in df.columns and df['match_date'].nunique() > 1:
        raise NotImplementedError(
            'Multiple match dates present: switch to a chronological split before evaluating. '
            'A random match-level split leaks future information once matches span time.'
        )

    match_ids = df['match_id'].unique()
    rng = np.random.RandomState(seed)
    rng.shuffle(match_ids)
    n_holdout = max(1, int(len(match_ids) * holdout_frac))
    holdout_ids = set(match_ids[:n_holdout])
    holdout = df[df['match_id'].isin(holdout_ids)]
    train = df[~df['match_id'].isin(holdout_ids)]

    assert not (set(train['match_id']) & set(holdout['match_id'])), 'match leaked across the split'
    return train, holdout


def decile_calibration(y_true, y_pred):
    frame = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    try:
        frame['bucket'] = pd.qcut(frame['y_pred'], 10, duplicates='drop')
    except ValueError:
        frame['bucket'] = pd.cut(frame['y_pred'], 10)
    grouped = frame.groupby('bucket', observed=True).agg(
        n=('y_true', 'size'), mean_predicted=('y_pred', 'mean'), actual_win_rate=('y_true', 'mean')
    )
    return grouped


def expected_calibration_error(grouped):
    """Sample-weighted mean |predicted - actual| across the deciles."""
    w = grouped['n'] / grouped['n'].sum()
    return float((w * (grouped['mean_predicted'] - grouped['actual_win_rate']).abs()).sum())


def git_sha():
    try:
        return subprocess.check_output(
            ['git', 'rev-parse', 'HEAD'], cwd=HERE, stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return 'unknown'


def main():
    data_path = os.path.join(HERE, 'data', 'real_matches.csv')
    df = pd.read_csv(data_path)

    train_df, holdout_df = match_level_split(df)
    model = RandomForestRegressor(n_estimators=50, random_state=RANDOM_STATE)
    model.fit(train_df[FEATURES], train_df['win_probability'])

    y_true = holdout_df['win_probability'].values
    y_pred = np.clip(model.predict(holdout_df[FEATURES]), 0, 1)

    brier = float(brier_score_loss(y_true, y_pred))
    # log loss is unbounded at exactly 0/1, and a fully-grown forest produces both. Clip only for
    # this metric, and record that we did.
    ll = float(log_loss(y_true, np.clip(y_pred, 1e-6, 1 - 1e-6), labels=[0, 1]))
    grouped = decile_calibration(y_true, y_pred)
    ece = expected_calibration_error(grouped)
    base_rate = float(y_true.mean())
    # Brier of the constant predictor. Any model must beat this to be worth deploying.
    baseline_brier = float(np.mean((y_true - base_rate) ** 2))

    metrics = {
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'git_sha': git_sha(),
        'seed': RANDOM_STATE,
        'evaluates': 'the training PROCEDURE via refit on the train split, not the deployed pickle '
                     '(which is refit on 100% of data)',
        'provenance': 'data/real_matches.csv is matchSimulator.js output - genuine outcome labels, '
                      'simulated cricket. Not evidence about real cricket.',
        'n_matches_total': int(df['match_id'].nunique()),
        'n_matches_train': int(train_df['match_id'].nunique()),
        'n_matches_holdout': int(holdout_df['match_id'].nunique()),
        'n_rows_train': int(len(train_df)),
        'n_rows_holdout': int(len(holdout_df)),
        'holdout_base_rate': round(base_rate, 5),
        'brier': round(brier, 5),
        'brier_constant_baseline': round(baseline_brier, 5),
        'brier_skill_vs_constant': round(1 - brier / baseline_brier, 5),
        'log_loss': round(ll, 5),
        'expected_calibration_error': round(ece, 5),
        'mean_predicted': round(float(y_pred.mean()), 5),
        'decile_calibration': [
            {
                'bucket': str(idx),
                'n': int(row['n']),
                'mean_predicted': round(float(row['mean_predicted']), 4),
                'actual_win_rate': round(float(row['actual_win_rate']), 4),
            }
            for idx, row in grouped.iterrows()
        ],
        'brier_ceiling': BRIER_CEILING,
        'passed': brier <= BRIER_CEILING,
    }

    out_dir = os.path.join(HERE, 'results', 'latest')
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, 'metrics.json'), 'w') as f:
        json.dump(metrics, f, indent=2)
        f.write('\n')

    print(json.dumps({k: v for k, v in metrics.items() if k != 'decile_calibration'}, indent=2))
    print('\nDecile calibration')
    print(grouped.to_string(float_format=lambda v: f'{v:.3f}'))

    if not metrics['passed']:
        raise SystemExit(f'FAIL: Brier {brier:.4f} exceeds ceiling {BRIER_CEILING}')
    print(f'\nPASS: Brier {brier:.4f} <= {BRIER_CEILING}')


if __name__ == '__main__':
    main()
