'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/AuthContext';
import { apiFetch } from '@/lib/apiFetch';
import Card from '@/components/ui/Card';
import Badge from '@/components/ui/Badge';

interface NewsPost {
  _id: string;
  title: string;
  category: string;
  body: string;
  author: { _id: string; name: string };
  createdAt: string;
  tournament: { _id: string; name: string } | null;
  match: string | null;
  heroPlayer: { _id: string; specialization?: string; user: { _id: string; name: string } } | null;
  isAutoGenerated: boolean;
}

export default function NewsDetailPage({ params }: { params: { id: string } }) {
  const { user } = useAuth();
  const router = useRouter();
  const [post, setPost] = useState<NewsPost | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/news/${params.id}`)
      .then(r => r.json())
      .then(data => { if (data.success) setPost(data.post); })
      .finally(() => setLoading(false));
  }, [params.id]);

  const handleDelete = async () => {
    if (!confirm('Delete this post?')) return;
    const res = await apiFetch(`/api/news/${params.id}`, { method: 'DELETE' });
    const data = await res.json();
    if (data.success) router.push('/news');
  };

  if (loading) {
    return <main className="flex items-center justify-center min-h-[calc(100vh-4rem)]"><p className="text-ink-secondary">Loading...</p></main>;
  }

  if (!post) {
    return <main className="flex items-center justify-center min-h-[calc(100vh-4rem)]"><p className="text-ink-secondary">Post not found.</p></main>;
  }

  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      <Link href="/news" className="text-sm text-pitch-400 hover:underline">&larr; Back to news</Link>
      <Card padding="lg" className="mt-4">
        <div className="flex justify-between items-start gap-3 mb-2">
          <h1 className="text-2xl font-bold text-ink">{post.title}</h1>
          <Badge variant="neutral" className="whitespace-nowrap">{post.category}</Badge>
        </div>
        {(post.tournament || post.isAutoGenerated) && (
          <div className="flex flex-wrap items-center gap-2 mb-2">
            {post.tournament && <Badge variant="info">{post.tournament.name}</Badge>}
            {post.isAutoGenerated && (
              <span className="text-xs text-ink-muted">🤖 Auto-generated match report</span>
            )}
          </div>
        )}
        <p className="text-sm text-ink-secondary mb-6">
          {post.author?.name ?? 'Unknown'} · {new Date(post.createdAt).toLocaleDateString()}
        </p>
        <div className="text-ink-secondary whitespace-pre-wrap leading-relaxed">{post.body}</div>

        {/* Boolean(...) on both sides - a bare equality reads as true for a logged-out viewer
            on a post with no author populated, since undefined === undefined. */}
        {Boolean(user?.id) && Boolean(post.author?._id) && user?.id === post.author?._id && (
          <button onClick={handleDelete} className="mt-6 text-sm text-wicket-500 hover:text-wicket-400 transition-colors">
            Delete post
          </button>
        )}
      </Card>
    </main>
  );
}
