// Verifies the optimizer actually recovers known coefficients before it's trusted with any
// experiment - the same reasoning as research/synthetic/generator.test.js: "we assumed the
// gradient descent converged" is exactly the kind of claim this research program exists to stop
// taking on faith. A hand-written Adam optimizer that silently fails to converge would produce a
// plausible-looking but meaningless comparison in Experiment 4B.
//
// Runs directly: `node research/models/regularizedHierarchicalLogit.test.js`
const assert = require('assert');
const { fitWithCrossValidatedLambda, buildDesign, fit, makePredictor, sigmoid } = require('./regularizedHierarchicalLogit');
const { makeRng } = require('../synthetic/generator');

function section(name, fn) {
  process.stdout.write(`${name} ... `);
  fn();
  console.log('OK');
}

function pearson(a, b) {
  const n = a.length;
  const meanA = a.reduce((s, x) => s + x, 0) / n;
  const meanB = b.reduce((s, x) => s + x, 0) / n;
  let num = 0, denA = 0, denB = 0;
  for (let i = 0; i < n; i++) {
    num += (a[i] - meanA) * (b[i] - meanB);
    denA += (a[i] - meanA) ** 2;
    denB += (b[i] - meanB) ** 2;
  }
  return num / Math.sqrt(denA * denB);
}

/** Generates data from a KNOWN additive logit model - deliberately independent of
 * synthetic/generator.js, so this tests the optimizer rather than re-testing the generator. */
function makeToyData({ numBatters, numBowlers, numRows, baseLogit, effectSd, seed }) {
  const rng = makeRng(seed);
  const trueBatter = Array.from({ length: numBatters }, () => rng.normal(0, effectSd));
  const trueBowler = Array.from({ length: numBowlers }, () => rng.normal(0, effectSd));
  const LINES = ['off-stump', 'leg-stump'];
  const LENGTHS = ['full', 'short'];
  const trueLL = new Map();
  for (const line of LINES) for (const length of LENGTHS) trueLL.set(`${line}|${length}`, rng.normal(0, effectSd));

  const rows = [];
  for (let i = 0; i < numRows; i++) {
    const b = rng.int(0, numBatters - 1);
    const w = rng.int(0, numBowlers - 1);
    const line = rng.pick(LINES);
    const length = rng.pick(LENGTHS);
    const z = baseLogit + trueBatter[b] + trueBowler[w] + trueLL.get(`${line}|${length}`);
    rows.push({
      batterId: `b${b}`,
      bowlerId: `w${w}`,
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Fast',
      line,
      length,
      isWicket: rng.bernoulli(sigmoid(z))
    });
  }
  return { rows, trueBatter, trueBowler, trueLL };
}

section('recovers known batter/bowler coefficients from data generated by a known additive logit model', () => {
  // A high base rate and large effects, with plenty of observations per player - if the optimizer
  // cannot recover coefficients HERE, it certainly cannot in the sparse cricket setting, so this
  // is the right first check to fail loudly.
  const { rows, trueBatter, trueBowler } = makeToyData({
    numBatters: 20, numBowlers: 20, numRows: 40000, baseLogit: -1.0, effectSd: 0.8, seed: 4242
  });
  const design = buildDesign(rows);
  const sizes = {
    batter: design.batterIdx.size, bowler: design.bowlerIdx.size,
    arch: design.archIdx.size, ll: design.llIdx.size, pair: design.pairIdx.size
  };
  // Light regularization here: the point is to check convergence to the truth, not shrinkage.
  const params = fit(design.encoded, sizes, { lambda: 1, lambdaInteraction: 1e6, maxIterations: 20000, learningRate: 0.05 });

  const estBatter = [], refBatter = [];
  for (const [key, idx] of design.batterIdx.entries()) {
    estBatter.push(params.batter[idx]);
    refBatter.push(trueBatter[Number(key.slice(1))]);
  }
  const estBowler = [], refBowler = [];
  for (const [key, idx] of design.bowlerIdx.entries()) {
    estBowler.push(params.bowler[idx]);
    refBowler.push(trueBowler[Number(key.slice(1))]);
  }

  const rBatter = pearson(estBatter, refBatter);
  const rBowler = pearson(estBowler, refBowler);
  console.log(`\n    (batter coefficient correlation with truth: ${rBatter.toFixed(4)}, bowler: ${rBowler.toFixed(4)})`);
  assert.ok(rBatter > 0.9, `optimizer failed to recover batter effects (r=${rBatter.toFixed(4)})`);
  assert.ok(rBowler > 0.9, `optimizer failed to recover bowler effects (r=${rBowler.toFixed(4)})`);
});

section('the interaction penalty actually shrinks interaction coefficients toward zero', () => {
  // Data generated with NO interaction effect at all - a heavily-penalized interaction term
  // should stay near zero rather than absorbing noise, which is the whole reason it carries a
  // separate, larger penalty (experiment-4-design.md).
  const { rows } = makeToyData({ numBatters: 15, numBowlers: 15, numRows: 8000, baseLogit: -2.0, effectSd: 0.5, seed: 777 });
  const design = buildDesign(rows);
  const sizes = {
    batter: design.batterIdx.size, bowler: design.bowlerIdx.size,
    arch: design.archIdx.size, ll: design.llIdx.size, pair: design.pairIdx.size
  };
  const weak = fit(design.encoded, sizes, { lambda: 1, lambdaInteraction: 1, maxIterations: 20000, learningRate: 0.05 });
  const strong = fit(design.encoded, sizes, { lambda: 1, lambdaInteraction: 1000, maxIterations: 20000, learningRate: 0.05 });
  const meanAbs = (vec) => vec.reduce((s, x) => s + Math.abs(x), 0) / vec.length;
  const weakMag = meanAbs(weak.pair);
  const strongMag = meanAbs(strong.pair);
  console.log(`\n    (mean |interaction coefficient|: weak penalty ${weakMag.toFixed(5)}, strong penalty ${strongMag.toFixed(5)})`);
  assert.ok(strongMag < weakMag, 'a stronger interaction penalty should produce smaller interaction coefficients');
});

section('fitWithCrossValidatedLambda picks a lambda without touching held-out data, and beats an intercept-only model on genuinely held-out rows', () => {
  const { rows } = makeToyData({ numBatters: 25, numBowlers: 25, numRows: 20000, baseLogit: -1.5, effectSd: 0.7, seed: 31337 });
  const splitAt = Math.floor(rows.length * 0.8);
  const trainRows = rows.slice(0, splitAt);
  const heldOut = rows.slice(splitAt); // never seen by fitWithCrossValidatedLambda in any form

  const model = fitWithCrossValidatedLambda(trainRows, { });
  assert.ok([1, 5, 20, 100].includes(model.chosenLambda), `unexpected chosen lambda: ${model.chosenLambda}`);

  const baseRate = trainRows.reduce((s, r) => s + (r.isWicket ? 1 : 0), 0) / trainRows.length;
  const eps = 1e-12;
  const clip = (p) => Math.min(Math.max(p, eps), 1 - eps);
  let modelLoss = 0, interceptLoss = 0;
  for (const r of heldOut) {
    const p = clip(model.predict(r));
    const y = r.isWicket ? 1 : 0;
    modelLoss += y === 1 ? -Math.log(p) : -Math.log(1 - p);
    interceptLoss += y === 1 ? -Math.log(clip(baseRate)) : -Math.log(1 - clip(baseRate));
  }
  modelLoss /= heldOut.length;
  interceptLoss /= heldOut.length;
  console.log(`\n    (chosen lambda ${model.chosenLambda}; held-out log loss: model ${modelLoss.toFixed(5)} vs intercept-only ${interceptLoss.toFixed(5)})`);
  assert.ok(modelLoss < interceptLoss, `model should beat an intercept-only baseline on data with real structure (model=${modelLoss.toFixed(5)}, intercept=${interceptLoss.toFixed(5)})`);
});

section('unseen players fall back to the population average rather than crashing or producing NaN', () => {
  const { rows } = makeToyData({ numBatters: 10, numBowlers: 10, numRows: 3000, baseLogit: -2.0, effectSd: 0.5, seed: 5150 });
  const model = fitWithCrossValidatedLambda(rows, { });
  const p = model.predict({
    batterId: 'never_seen_batter', bowlerId: 'never_seen_bowler',
    battingStyle: 'Left-hand', bowlingStyle: 'Left-arm Spin', line: 'off-stump', length: 'full'
  });
  assert.ok(Number.isFinite(p) && p > 0 && p < 1, `expected a valid probability for an unseen player, got ${p}`);
});

section('the convergence criterion actually converges - doubling the iteration cap barely moves predictions', () => {
  // This check exists because its absence caused a real defect: Experiment 4 used a fixed
  // 300-iteration budget that was NOT converged (predictions moved ~1.3e-3 between 300 and 600
  // iterations, the same order as the Brier differences between the methods being compared). A
  // fixed iteration count silently conflates "this model is better" with "this model's optimizer
  // ran longer." The tolerance-based stopping rule must be verified, not assumed.
  const { rows } = makeToyData({ numBatters: 30, numBowlers: 25, numRows: 15000, baseLogit: -2.5, effectSd: 0.6, seed: 90210 });
  const design = buildDesign(rows);
  const sizes = {
    batter: design.batterIdx.size, bowler: design.bowlerIdx.size,
    arch: design.archIdx.size, ll: design.llIdx.size, pair: design.pairIdx.size
  };
  const opts = { lambda: 5, lambdaInteraction: 20, learningRate: 0.05 };
  const converged = fit(design.encoded, sizes, { ...opts, maxIterations: 20000, tolerance: 1e-9 });
  const stricter = fit(design.encoded, sizes, { ...opts, maxIterations: 40000, tolerance: 1e-11 });

  const predA = makePredictor(converged, design);
  const predB = makePredictor(stricter, design);
  const probes = rows.slice(0, 300);
  let maxAbs = 0;
  for (const r of probes) maxAbs = Math.max(maxAbs, Math.abs(predA(r) - predB(r)));
  console.log(`\n    (stopped at ${converged.iterationsRun} iterations; max prediction shift vs a 100x stricter tolerance: ${maxAbs.toExponential(3)})`);
  assert.ok(converged.iterationsRun < 20000, 'fit hit the iteration cap instead of converging');
  assert.ok(maxAbs < 1e-4, `predictions still moving after the convergence criterion fired (max shift ${maxAbs.toExponential(3)}) - the tolerance is too loose to trust`);
});

console.log('\nAll regularizedHierarchicalLogit verification checks passed.');
