'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/AuthContext';
import { apiFetch } from '@/lib/apiFetch';
import Card from '@/components/ui/Card';
import Badge from '@/components/ui/Badge';
import PageHeader from '@/components/ui/PageHeader';
import EmptyState from '@/components/ui/EmptyState';
import { buttonVariants } from '@/components/ui/buttonStyles';

interface NewsPost {
  _id: string;
  title: string;
  category: string;
  body: string;
  author: { name: string };
  createdAt: string;
  tournament: { _id: string; name: string } | null;
  match: string | null;
  heroPlayer: { _id: string; specialization?: string; user: { _id: string; name: string } } | null;
  isAutoGenerated: boolean;
}

type FeedMode = 'public' | 'mine';

export default function NewsPage() {
  const { user } = useAuth();
  const [posts, setPosts] = useState<NewsPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [feedMode, setFeedMode] = useState<FeedMode>('public');
  const canPost = user && ['organizer', 'admin'].includes(user.role);

  // If the user logs out while on the personalized tab, fall back to the public feed.
  useEffect(() => {
    if (!user && feedMode === 'mine') setFeedMode('public');
  }, [user, feedMode]);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    const load = async () => {
      try {
        const res = feedMode === 'mine' && user
          ? await apiFetch('/api/news/feed')
          : await fetch('/api/news');
        const data = await res.json();
        if (!cancelled && data.success) setPosts(data.posts);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => { cancelled = true; };
  }, [feedMode, user]);

  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      <PageHeader
        title="News"
        description="Announcements and updates from organizers."
        action={canPost ? <Link href="/news/new" className={buttonVariants('primary')}>+ New Post</Link> : undefined}
      />

      {user && (
        <div className="flex gap-2 mb-6">
          <button
            onClick={() => setFeedMode('public')}
            className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${feedMode === 'public' ? 'bg-pitch-500 text-[#06170D]' : 'bg-surface-alt text-ink-secondary hover:text-ink'}`}
          >
            All News
          </button>
          <button
            onClick={() => setFeedMode('mine')}
            className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${feedMode === 'mine' ? 'bg-pitch-500 text-[#06170D]' : 'bg-surface-alt text-ink-secondary hover:text-ink'}`}
          >
            My Tournaments
          </button>
        </div>
      )}

      {loading ? (
        <p className="text-ink-secondary">Loading...</p>
      ) : posts.length === 0 ? (
        <EmptyState
          icon="📰"
          title={feedMode === 'mine' ? 'No news for your tournaments yet' : 'No news yet'}
        />
      ) : (
        <div className="space-y-3">
          {posts.map(p => (
            <Link key={p._id} href={`/news/${p._id}`}>
              <Card hover>
                <div className="flex justify-between items-start gap-3">
                  <h2 className="font-semibold text-ink">{p.title}</h2>
                  <Badge variant="neutral">{p.category}</Badge>
                </div>
                {(p.tournament || p.isAutoGenerated) && (
                  <div className="flex flex-wrap items-center gap-2 mt-2">
                    {p.tournament && <Badge variant="info">{p.tournament.name}</Badge>}
                    {p.isAutoGenerated && (
                      <span className="text-xs text-ink-muted">🤖 Auto-generated match report</span>
                    )}
                  </div>
                )}
                <p className="text-sm text-ink-secondary mt-2">
                  {p.author?.name ?? 'Unknown'} · {new Date(p.createdAt).toLocaleDateString()}
                </p>
                <p className="text-sm text-ink-secondary mt-2 line-clamp-2">{p.body.slice(0, 160)}{p.body.length > 160 ? '...' : ''}</p>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </main>
  );
}
